#!/bin/bash
precmd() {
    # colors
    local red="%{$fg[red]%}"
    local green="%{$fg[green]%}"
    local reset="%{$reset_color%}"
    local yellow="%{$fg[yellow]%}" 
    local white="%{$fg[white]%}" 
    local blue="%{$fg[blue]%}" 
    # components
    local name="%(!.$red.$green)%n$reset"
    local hostname="$yellow%m$reset"
    local dirname="$white%64<.<%~$reset"
    local time="$blue$(date "+%-I:%M%p")$reset"
    local hash="%(!.#.$)"

    export PROMPT="
$name@$hostname:$dirname%) $(_git_status)
$time$hash "
}

_git_status() {
    if $(git rev-parse --is-inside-work-tree 2> /dev/null); then
        echo "$(_refs)%)"
    else
        echo ""
    fi
}

_refs() {
    if [[ "$(git rev-parse --all)" == "" ]]; then
        echo "new"
    else
        echo $(_branch)
    fi
}

_branch() {
    local branch="$(git rev-parse --abbrev-ref HEAD)"
    if [[ "$branch" == "HEAD" ]]; then
        local detached="detached@$(git rev-parse --short HEAD)"
        echo "$red$detached$reset"
    else
        echo $(_porcelain)
    fi
}

_porcelain() {
    if [[ "$(git status --porcelain)" == "" ]]; then
        echo "$green$branch$reset"
    else
        echo "$red$branch$reset"
    fi
}
