#!/bin/bash
alias l="ls -G"
alias la="l -A"
alias ll="l -hl"
alias lla="l -Ahl"
alias lm="ll | more"
alias cp="cp -i"
alias mv="mv -i"
#alias reset_dock="_reset_dock"

alias gc="git checkout --no-guess"
alias gcb="gc -b"
alias gco="git commit"
alias gd="git diff"
#alias gpu="_gpu"
alias gs="git status"

alias asit="adb shell input text"
alias simulator="open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app"
search() {
    if [[ -z "$2" ]]; then
        find . -iname "*$1*" -type f
    else
        find . -iname "*$1*" -type f -exec $2 {} \+
    fi
}

alias caesar="rename y/A-Za-z/N-ZA-Mn-za-m/"
