#!/bin/bash
alias l="ls -G"
alias la="l -A"
alias ll="l -hl"
alias lla="l -Ahl"
alias lm="ll | more"
alias cp="cp -i"
alias mv="mv -i"
#alias reset_dock="_reset_dock"

alias gc="git checkout --no-guess"
alias gcb="gc -b"
alias gco="git commit"
alias gd="git diff"
#alias gpu="_gpu"
alias gs="git status"

alias grhH="git reset --hard HEAD"

alias asit="adb shell input text"
alias simulator="open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app"

alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --disable-features=PreloadMediaEngagementData,AutoplayIgnoreWebAudio,MediaEngagementBypassAutoplayPolicies"
