#!/bin/bash
precmd() {
    # colors
    local red="%{$fg[red]%}"
    local green="%{$fg[green]%}"
    local reset="%{$reset_color%}"
    local yellow="%{$fg[yellow]%}"
    local white="%{$fg[white]%}"
    local blue="%{$fg[blue]%}"
    # components
    local name="%(!.$red.$green)%n$reset"
    local hostname="$yellow%m$reset"
    #local dirname="$white%64<.<%~$reset"
    local dirname="$gray%64<.<%~$reset"
    local time="$blue$(date "+%-I:%M%p")$reset"
    local hash="%(!.#.$)"

    export PROMPT="
$name@$hostname:$dirname%) $(git_status__)
$time$hash "
}

git_status__() {
    if $(git rev-parse --is-inside-work-tree 2> /dev/null); then
        echo "$(refs__)%)"
    else
        echo ""
    fi
}

refs__() {
    if [[ "$(git rev-parse --all)" == "" ]]; then
        echo "new"
    else
        echo $(branch__)
    fi
}

branch__() {
    local branch="$(git rev-parse --abbrev-ref HEAD)"
    if [[ "$branch" == "HEAD" ]]; then
        local detached="detached@$(git rev-parse --short HEAD)"
        echo "$red$detached$reset"
    else
        echo $(porcelain__)
    fi
}

porcelain__() {
    if [[ "$(git status --porcelain)" == "" ]]; then
        echo "$green$branch$reset"
    else
        echo "$red$branch$reset"
    fi
}
