#!/bin/bash
#reset_dock() {
#    defaults write com.apple.dock ResetLaunchPad -bool true; killall Dock
#}

housekeeping() {
    git fetch -p && for branch in `git branch -vv | grep ': gone]' | awk '{print $1}'`; do git branch -D $branch; done
}

gpu() {
    local branch="$(git rev-parse --abbrev-ref HEAD)"
    git push -u origin "$branch"
}

gw() {
    $(_upfind gradlew) "$@"
}

_upfind() {
   local dir=$(pwd)
   while [[ "$dir" != "/" ]]; do
      local local_path=$(find "$dir" -maxdepth 1 -name $1)
      if [[ "$local_path" != "" ]]; then
         echo "$local_path"
         return
      fi
      dir=$(dirname "$dir")
    done
}
